Connect group interactions and poll creation to api
HE-Arc/1d6 pull request #111
Opened 2019-12-15 17:07 UTC by g-wizzy

Features a massive refactor on the groups page.

Close #110 close #30

#82 and #82 could be closed by this, but the API needs to be tested.

Would close

2019-12-15 17:11 UTC, g-wizzy commented on resources/js/components/pages/create-poll.vue
> +        users: [{ name: localStorage.getItem("username") + " (You)" }],
Forgot to remove this default value. It is overridden on page load anyway. I'll remove it along with other corrections if there are any.

2019-12-16 13:42 UTC, Blatoy requested changes

2019-12-16 13:42 UTC, Blatoy commented on app/Http/Resources/GroupResource.php
> +            'userCount' => $this->users()->count(),
Please use snake case

2019-12-16 13:42 UTC, Blatoy commented on resources/js/components/groups/add-group-modal.vue
> +        id: localStorage.getItem("id"),
Do we have id in localstorage?

2019-12-16 13:42 UTC, Blatoy commented on resources/js/components/groups/add-group-modal.vue
> +        .get("/users/by-mail/" + email)
Missing `encodedURIComponent` for the email

2019-12-16 13:42 UTC, Blatoy commented on resources/js/components/groups/edit-group-modal.vue
> +        users_to_add: this.usersToAdd.map(user => user.id),
users_to_add should receive
`[{"id": <id>, "admin": <bool>}]`
users_to_remove and items_to_remove should receive
`[{"id": <id>}]`

2019-12-16 13:42 UTC, Blatoy commented on resources/js/components/pages/create-poll.vue
> +        .get("/users/by-mail/" + email)
Missing `encodeURIComponent`

2019-12-16 14:12 UTC, g-wizzy commented on resources/js/components/groups/add-group-modal.vue
> +        id: localStorage.getItem("id"),
Yes we do

2019-12-16 14:27 UTC, Blatoy approved these changes

2019-12-16 14:27 UTC, merged